version: 2.1

jobs:

  Build-Source-Code-Dev:
    working_directory: ~/tq
    docker:
      - image: circleci/node:17.2-browsers

    steps:      
      - checkout
      - restore_cache:
          key: tq-{{ .Branch }}-{{ checksum "package.json" }}
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: tq-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: Build Source Code
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              echo 'Beginning build...'
              npm run build-dev
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .

  Deploy-Source-Code-Dev:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy To AWS-S3
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              echo 'Beginning deploy ...'
              aws s3 sync dist/angular-test-app/ s3://tqng/ --delete --exact-timestamps;
            fi          

workflows:
  Development:
    jobs:
      - Build-Source-Code-Dev
      - Deploy-Source-Code-Dev:
          requires: 
            - Build-Source-Code-Dev
