version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Repository Files 
          command: |
            ls -al
            echo 'End Transmission...'